version: '3.8'

services:
  backend:
    container_name: backend
    build: ./docker
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    links:
      - "database"
    # command: >
      # sh -c "composer install && php artisan key:generate && php artisan serve"

  database:
    container_name: database
    image: mysql:8.0
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: my_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
    ports:
     - "3306:3306"